config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  resources :charges, only: [:new, :create]

  authenticated :user do
  	root "docs#index", as: "authenticated_root"
  end 

  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user

  def content_word_count
  	content&.split(' ')&.size.to_i
  end
  def time_taken
  	
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  rescue_from Stripe::CardError, with: :catch_exception
  def new
  end

  def create
    StripeChargesServices.new(charges_params).call
    redirect_to root_path
  end

  private

  def charges_params
    params.permit(:stripeEmail, :stripeToken)
  end

  def catch_exception(exception)
    flash[:error] = exception.message
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
	before_action :find_doc, only: [:show, :edit, :update, :destroy]
	def index
		@docs = Doc.where(user_id: current_user)
	end

	def show
		
	end

	def new
		@doc = current_user.docs.build
	end

	def create
		@doc = current_user.docs.build(doc_params)
		if @doc.save
			redirect_to @doc
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @doc.update(doc_params)
			redirect_to @doc
		else
			render 'edit'
		end
	end

	def destroy
		@doc.destroy
		redirect_to docs_path
	end

	private
	   def find_doc
	   	  @doc = Doc.find(params[:id])
	   end

	   def doc_params
	   	  params.require(:doc).permit(:title, :content) 
	   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>
    <label class="amount">
    <span>Amount: $<%= 100 %></span>
    </label>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="A month's subscription"
    data-amount="<%= 100 %>"
    data-locale="auto"></script>
<% end %>

<script src="https://js.stripe.com/v2/"></script>

<script>
  Stripe.setPublishableKey('pk_test_nM7VaB7XTlhd7eg7AT7yuc1a00bJnb2C3D');
</script>

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>

	<div style="margin: 10px;">
    <p id="time-board">
      you have taken <span><%= @doc.time_taken.to_i %></span> seconds
    </p>
		  <div id="start-time" class="button" style="float: right;margin-bottom: 20px;">
		    Start Time
		  </div>
		  <div id="end-time" class="hidden button" style="float: right;margin-bottom: 20px;">
		     End Time
		  </div>
	</div>


  <%= f.hidden_field :time_taken, value: @doc.time_taken.to_i %>
  <%= f.input :title %>
  <p style="float: right; margin-bottom: 20px;">
      <span id="time-taken"><%= f.hidden_field :time_taken %></span>
  </p>


  <div>
    <%= f.input :content %>
    <p style="margin: 0;float: right;">
      Word count:
      <span id="content-word-count"><%= @doc.content_word_count %></span>
    </p>
  </div>
  <%= f.button :submit, id: 'doc-submit-button' %>
  <a href="https://www.oxfordlearnersdictionaries.com/" style="margin-left: 270px" class="button">Dictonary</a>
  <a href="https://thesaurus.yourdictionary.com/" style="margin-left: 100px" class="button">Synonyms/Antonyms</a>
<% end %>

app/views/docs/edit.html.haml
.wrapper_with_padding
	%h1 Fix Doc!

	= render 'form'
	= link_to "cancel", doc_path

app/views/docs/index.html.haml
.wrapper_with_padding
	#docs.clearfix
		-unless @docs.blank?
			- @docs.each do |doc|
				%a{ href: (url_for [doc])}
					.doc
						%p.title= doc.title
						%p.date= time_ago_in_words(doc.created_at)
						%p.content= truncate(doc.content, lenght:50)

		- else
			%h2 create doc !
			%p Start creating Documents and organising your life!
			%button= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
.wrapper_with_padding
	%h1 New Doc !

	= render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding 
	#doc_show
		%h1.title= @doc.title
		%p= simple_format(@doc.content)

		.buttons
			= link_to "Fix Doc", edit_doc_path(@doc), class: "button"
			= link_to "Trash it", doc_path(@doc), method: :delete, data: {confirm: "Are you sure ?"}, class: "button"

app/views/layouts/application.html.haml
!!!
%html 
%head
  %title Automated Text Analysis | your life's work !
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to "ATA", root_path, id: "logo"

      %nav
        - if user_signed_in?
          = link_to "create doc", new_doc_path
          = link_to "sign out", destroy_user_session_path, method: :delete

        - else 
          = link_to "Log in", new_user_session_path
        = link_to "Premium", new_charge_path
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/welcome/index.html.haml
#banner 
	.banner_content
		%h1 Automated Text Analysis
		%p your life's work. organized, always.
		%button= link_to "Enter", new_user_registration_path

#callouts
	.callout_inner
		.wrapper
			.callout
				%h2 Organized
				%p Minor Project
				
#bottom_cta
	.wrapper
		%h3 Go Ahead
		%br
		%button= link_to "Join Now", new_user_registration_path